<?php
//
require_once("../../include.php");
//
$l->createHeader();
$l->addJavascripts(array("javascripts/inup_drink.js"));
$l->createPageTitleBar($def_title,$dict["INSERT_DRINK"]);
//
//######################################################################################
$l->createInupForm(
	array(
	"name",
	)
);
//
//
$l->createFooter();
//
?>
