<?php
//
require_once("../../include.php");
//
$l->createHeader();
$l->addJavascripts(array("javascripts/menu.js"));
//creazione di un array per le icone del menu
$images_arr=array(
	array(
		"name"=>$dict["TITLE_HOME"],
		"url"=>"../home/home.php",
		"img_src"=>"../../images/home.svg",
	),
	array(
		"name"=>$dict["TITLE_DRINK"],
		"url"=>"../drink/list_drink.php",
		"img_src"=>"../../images/drink.svg",
	),
	array(
		"name"=>$dict["TITLE_FOOD"],
		"url"=>"../food/list_food.php",
		"img_src"=>"../../images/food.svg",
	),
	array(
		"name"=>$dict["TITLE_TABLE"],
		"url"=>"../table/list_table.php",
		"img_src"=>"../../images/table.svg",
	),
	array(
		"name"=>$dict["TITLE_MESSAGE"],
		"url"=>"../message/message.php",
		"img_src"=>"../../images/message.svg",
	),
);
//
$l->createIconMenu($images_arr,$def_right_frame);
//
$l->createFooter();
//
?>
