<?php
//
require_once("../../include.php");
//
$l->createHeader();
$l->createPageTitleBar($def_title,$dict["TITLE_HOME"]);
//$l->addJavascripts(array("javascripts/bubble_chart.js"));
//$l->addJavascripts(array("javascripts/bar_chart.js"));
$l->createFooter();
//
?>
